services:
  server:
    build:
      context: .
      dockerfile: ./src/server/Dockerfile
    container_name: udp_server
    networks:
      chat_net:
        ipv4_address: 192.168.1.10
    ports:
      - "7896:7896"

  client:
    build:
      context: .
      dockerfile: ./src/client/Dockerfile
    container_name: udp_client
    networks:
      chat_net:
        ipv4_address: 192.168.1.11
    environment:
      SERVER_HOST: 192.168.1.10

networks:
  chat_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
